<div class="gallery-item isotope-item print-media col-lg-4 col-sm-4 col-xs-6">
                <div class="inner-contents">
                  <figure> <a class="gallery-btn swipebox" href="[field:picname/]">查看更多</a>
                    <div class="media-container"></div>
                    <img src="[field:picname/]" alt="[field:title/]"/> </figure>
                  <h5 class="item-title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h5>
                </div>
              </div>