<div class="row">
              <div class="col-md-12">
                  <div class="section-heading text-center">
                      <h1><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></h1>
                      <p>{dede:field name='description'/}</p>
                  </div>
              </div>
          </div>
          <div class="row">
              {dede:field name='content'/}
          </div>