<div class="blog-article hentry format-image">
            <figure> <a class="c-thumblink" href="[field:arcurl/]"> <img class="img-responsive" alt="[field:title/]" src="[field:picname/]"/> </a> </figure>
            <div class="entry-summary post-summary">
              <header class="entry-header">
                <h2 class="entry-title post-title"> <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a> </h2>
              </header>
              <div class="entry-content">
                <p class="d-desc">[field:description function="cn_substr(@me,200)"/]...</p>
              </div>
              <a href="[field:arcurl/]" class="read-more-date">[field:activitytime function='strftime("%Y-%m-%d",@me)'/]</a> 
            </div>
          </div>