<?php
$z[0]=Array("arcurl","",29,44);
$z[0][4]=array();
$z[1]=Array("activitytime","",193,244);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%m\",@me)";
$z[2]=Array("activitytime","",355,406);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("title","",555,569);
$z[3][4]=array();
$z[4]=Array("description","",619,639);
$z[4][4]=array();
$z[5]=Array("activitytime","",686,737);
$z[5][4]=array();
$z[5][4]['function']="strftime(\"%Y\",@me)";

?>