<div class="blog-article hentry format-image">
            <figure style="width: 150px;"> <a class="swipebox-x" href="[field:arcurl/]"> <img style="height: 180px;" class="img-responsive" alt="[field:title/]" src="[field:picname/]"/> </a> </figure>
            <div class="entry-summary post-summary">
              <header class="entry-header">
                <h2 class="entry-title post-title"> <a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a> </h2>
              </header>
              <div class="entry-content">
                <p>[field:description function="cn_substr(@me,400)"/]...</p>
              </div>
              <a href="[field:arcurl/]" class="read-more-link">查看详细</a> </div>
          </div>