<li>
                <a href="[field:arcurl/]" target="_blank">
                  <img src="[field:picname/]" />
                  <div class="platform-items-desc">
                      <p class="desc-title">[field:title/]</p>
                      <p class="desc-content">[field:description function='cn_substr(Html2text(@me),60)'/]...</p>
                </div>
                </a>
              </li>