<?php
$z[0]=Array("field","",70,98);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",100,129);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                    <li><a  href=\"[field:arcurl/]\"><em class=\"news-title\">[field:title /]</em><em class=\"news-date\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</em></a></li>\r\n                ",236,518);
$z[2][4]=array();
$z[2][4]['titlelen']="200";
$z[2][4]['orderway']="desc";
$z[2][4]['orderby']="pubdate";

?>