<?php
$z[0]=Array("field","",224,252);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",254,283);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",307,339);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("arclist","\r\n      <div class=\"col-md-3 col-sm-6 col-xs-6 case-item\">\r\n        <div class=\"books-item\">\r\n          <p class=\"thumb-link\"><a href=\"[field:arcurl/]\"><img alt=\"[field:title/]\" src=\"[field:picname/]\"/></a></p>\r\n          <h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n        </div>\r\n      </div>\r\n      ",409,814);
$z[3][4]=array();
$z[3][4]['row']="4";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";

?>