<?php
$z[0]=Array("arcurl","",29,44);
$z[0][4]=array();
$z[1]=Array("pubdate","",193,239);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%m\",@me)";
$z[2]=Array("pubdate","",350,396);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("title","",545,559);
$z[3][4]=array();
$z[4]=Array("description","",609,629);
$z[4][4]=array();
$z[5]=Array("pubdate","",676,722);
$z[5][4]=array();
$z[5][4]['function']="strftime(\"%Y\",@me)";

?>