
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>












<field:course itemname="选择咨询内容" autofield="1" type="select" isnull="true" default="产业互联网创新领袖计划,标杆企业游学参访,企业内训,公开课,其他游学参访"  maxlength="250" page="">
</field:course>




