<?php
$z[0]=Array("field","",108,166);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n                  <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n                  ",257,551);
$z[1][4]=array();
$z[1][4]['row']="10";
$z[1][4]['type']="son";
$z[1][4]['col']="1";
$z[1][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[2]=Array("include","",594,637);
$z[2][4]=array();
$z[2][4]['filename']="online_apply.htm";

?>