<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('442', '/uploads/allimg/200428/1-20042QIR30-L.jpg');
$maNum = 1;
$myaddons[$maNum] = array('443', '/uploads/allimg/200428/1-20042QI9130-L.jpg');
$maNum = 2;
$myaddons[$maNum] = array('444', '/uploads/allimg/200428/1-20042QI9500-L.jpg');
$maNum = 3;
$myaddons[$maNum] = array('445', '/uploads/allimg/200428/1-20042QJ0400-L.jpg');
$maNum = 4;
