<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('411', '/uploads/allimg/200416/1-2004161A534934.jpg');
$maNum = 1;
$myaddons[$maNum] = array('412', '/uploads/200416/1-2004161J25J48.jpg');
$maNum = 2;
$myaddons[$maNum] = array('413', '/uploads/200416/1-2004161J25J48-lp.jpg');
$maNum = 3;
$myaddons[$maNum] = array('414', '/uploads/200416/1-2004161P43Ec.jpg');
$maNum = 4;
$myaddons[$maNum] = array('417', '/uploads/200416/200417/1-20041F9102ME.jpg');
$maNum = 5;
$myaddons[$maNum] = array('418', '/uploads/200417/1-20041F9462GT.jpg');
$maNum = 6;
$myaddons[$maNum] = array('419', '/uploads/180305/200417/1-20041F94FJ14.jpg');
$maNum = 7;
